#!/bin/bash
echo -e '\e[40m\e[92m'
echo -e 'bbbbbbbb'
echo -e 'b::::::b            lllllll  333333333333333'
echo -e 'b::::::b            l:::::l 3:::::::::::::::33'
echo -e 'b::::::b            l:::::l 3::::::33333::::::3'
echo -e ' b:::::b            l:::::l 3333333     3:::::3'
echo -e ' b:::::bbbbbbbbb     l::::l             3:::::3uuuuuu    uuuuuu'
echo -e ' b::::::::::::::bb   l::::l             3:::::3u::::u    u::::u'
echo -e ' b::::::::::::::::b  l::::l     33333333:::::3 u::::u    u::::u'
echo -e ' b:::::bbbbb:::::::b l::::l     3:::::::::::3  u::::u    u::::u'
echo -e ' b:::::b    b::::::b l::::l     33333333:::::3 u::::u    u::::u'
echo -e ' b:::::b     b:::::b l::::l             3:::::3u::::u    u::::u'
echo -e ' b:::::b     b:::::b l::::l             3:::::3u::::u    u::::u'
echo -e ' b:::::b     b:::::b l::::l             3:::::3u:::::uuuu:::::u'
echo -e ' b:::::bbbbbb::::::bl::::::l3333333     3:::::3u:::::::::::::::uu'
echo -e ' b::::::::::::::::b l::::::l3::::::33333::::::3 u:::::::::::::::u'
echo -e ' b:::::::::::::::b  l::::::l3:::::::::::::::33   uu::::::::uu:::u'
echo -e ' bbbbbbbbbbbbbbbb   llllllll 333333333333333       uuuuuuuu  uuuu'
echo -e '\e[0m'
